### ISSUE TITLE
Tilde ~ sometimes not quoted

### ISSUE THREAD

**Issue by drok** [ljharb/shell-quote#13] opened 2023-11-05 06:20 UTC
Ref: https://github.com/ljharb/shell-quote/issues/9

The tilde needs to be quoted because there is an entire chapter of possibilities for Tilde expansion in the [bash manpage](https://www.man7.org/linux/man-pages/man1/bash.1.html#EXPANSION), other than the obvious shorthand for the `${HOME}` expression.

**Comment by ljharb** [comment] 2023-11-05 06:23
This is a duplicate of #9; please comment further there.

**Closed by ljharb** 2023-11-05 06:23 UTC

**Comment by drok** [comment] 2023-11-05 06:49
Very sorry, I meant to reference this issue in my repo, but accidentally added a dupe to yours. My sincere apologies!
